apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: clam-elasticsearch
spec:
  version: 7.8.1
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              readinessProbe:
                exec:
                  command:
                    - bash
                    - -c
                    - /mnt/elastic-internal/scripts/readiness-probe-script.sh
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 5
                successThreshold: 1
                timeoutSeconds: 5
              env:
                - name: READINESS_PROBE_TIMEOUT
                  value: "3"
          initContainers:
            - name: sysctl-mmap
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
            - name: sysctl-swapoff
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.swappiness=1"]
            - name: sysctl-tcp-retries
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w net.ipv4.tcp_retries2=5"]
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: standard
